### ISSUE TITLE
Unexplained incompatibility

### ISSUE THREAD

**Issue by marcusjhdon** [phpseclib/mcrypt_compat#10]
I've been trying to replace some legacy mcrypt functions with openssl equivalents, but even though the cipher and mode (MCRYPT_TRIPLEDES and MCRYPT_MODE_ECB) are apparently supported, I haven't been able to get it to work. So, I tried installing your shim/polyfill instead, but this also doesn't seem to work for this particular use case.

Here is some code to reproduce the problem. When run under PHP 5.6.30 with mcrypt enabled, it works fine, but if I disable mcrypt and use your polyfill it doesn't.

```PHP
$string = 'Password:abc123';
$expected = base64_decode('UEFjUYBUmsVnm7WU1fBfGQ==');

$td = mcrypt_module_open(MCRYPT_TRIPLEDES, '', MCRYPT_MODE_ECB, '');
$iv = mcrypt_create_iv(mcrypt_enc_get_iv_size($td), MCRYPT_RAND);
mcrypt_generic_init($td, '123456789abcdefg', $iv);
$result = mcrypt_generic($td, $string);
mcrypt_generic_deinit($td);

echo $result == $expected ? "PASS\n" : "FAIL\n";
```

**Comment by terrafrost** [comment]
I'll try to check it out this evening or within the next few days as time permits.

Thanks!

**Comment by terrafrost** [comment]
Your code snippet doesn't define `$expected`. But that said, the issue is due to the fact that the key is 16 bytes long instead of 24 bytes long. mcrypt null pads the key, phpseclib, in this particular case, employees 2TDEA or "keying option 2" or whatever it's best called. wikipedia elaborates:

https://en.wikipedia.org/wiki/Triple_DES#Keying_options

**Comment by terrafrost** [comment]
Anyway, I'll work on a fix - thanks for pointing this out!

**Comment by marcusjhdon** [comment]
I've updated the code snippet with the missing declarations.

Thanks for the fast replies BTW!

**Comment by terrafrost** [comment]
The 1.0.3 release should fix this.

Thanks!
