### ISSUE TITLE
RIJNDAEL-128 ECB Mode doesn't use IV but this polyfill requires a 16-bit IV

### ISSUE THREAD

**Issue by michaelbutler** [phpseclib/mcrypt_compat#12]
Using original mcrypt extension, this works:

```php
>>> $key = str_repeat('a', 32);
=> "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
>>> $data = 'Hello world! ';
=> "Hello world! "
>>> $encrypted = @mcrypt_encrypt(MCRYPT_RIJNDAEL_128, $key, $data, MCRYPT_MODE_ECB);
PHP Deprecated:  Function mcrypt_encrypt() is deprecated on line 1
=> (binary data)
>>> echo bin2hex($encrypted) . PHP_EOL;
15095a3abbc6ecff1bed490d1396a0c7
```

However when running the code with this polyfill (after removing mcrypt extension) a warning is raised and `false` is returned:

```
PHP Warning:  mcrypt_encrypt(): Received initialization vector of size  0, but size 16 is required for this encryption mode in /Users/username/tmp/mcrypt_compat/lib/mcrypt.php on line 970
```

Here's my test script:

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/lib/mcrypt.php';

$key = str_repeat('a', 32);
$data = 'Hello world! ƒ';
$encrypted = mcrypt_encrypt(MCRYPT_RIJNDAEL_128, $key, $data, MCRYPT_MODE_ECB, '');
echo bin2hex($encrypted) . PHP_EOL;
```

I've tried using `''` as well as `null` for the IV and got similar result.

**Comment by michaelbutler** [comment]
Note: deprecation notice is due to running on 7.1, ignore that.

**Comment by michaelbutler** [comment]
Apologies, did not see this pull request: https://github.com/phpseclib/mcrypt_compat/pull/11 but glad to see it's being worked on! Might as well keep this issue open until the change gets merged in case anyone else searches for this.

**Comment by terrafrost** [comment]
#11 has been merged and a new release that should fix this issue has been tagged.

Thanks!
