### ISSUE TITLE
create_function deprecated in PHP 7.2

### ISSUE THREAD

**Issue by CraigChaffee** [phpseclib/mcrypt_compat#14]
Deprecated functionality: Function create_function() is deprecated  in /var/www/vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php on line 2495

We're trying to use this library to move to 7.2 but the code uses a deprecated method and throws a warning.

**Comment by terrafrost** [comment]
That was fixed in phpseclib 2.0.7 (which was released last year):

https://github.com/phpseclib/phpseclib/commit/f4b6a522dfa1fd1e477c9cfe5909d5b31f098c0b

mcrypt_compat requires `~2.0`. This means it requires phpseclib >=2.0 < 3.0.0. Maybe when you initially installed phpseclib the latest version was 2.0.6 or something but that is now no longer the case.

I think `composer update` should fix the issue for you.

**Comment by CraigChaffee** [comment]
Thanks! I'll test it.

I confirmed the README.md instructions to run `composer require phpseclib/mcrypt_compat` installs v1.0.4 of phpseclib.

**Comment by CraigChaffee** [comment]
Updating phpseclib/phpseclib to the latest one indeed fixes the issue. Thanks!

So should mcrypt_compat/composer.json:25 be "phpseclib/phpseclib": ">=2.0.7" ?

**Comment by terrafrost** [comment]
I just did `composer require phpseclib/mcrypt_compat` in a brand new directory and it installed 2.0.10 of phpseclib/phpseclib and 1.0.4 of phpseclib/mcrypt_compat for me:

```
$ composer require phpseclib/mcrypt_compat
Using version ^1.0 for phpseclib/mcrypt_compat
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing phpseclib/phpseclib (2.0.10): Loading from cache
  - Installing phpseclib/mcrypt_compat (1.0.4): Loading from cache
phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodi
um-php extension.)
phpseclib/phpseclib suggests installing ext-mcrypt (Install the Mcrypt extension in order to speed up a few other crypto
graphic operations.)
Writing lock file
Generating autoload files
```

I don't see how 1.0.4 of phpseclib could be installed when composer.json says `"phpseclib/phpseclib": "~2.0"`.

**Comment by CraigChaffee** [comment]
I had the master branch version. Where the composer file has:
"phpseclib/phpseclib": "dev-master"

Not sure how that happened, but it's safe to assume I just did something horribly wrong. Thanks for all your help. I'll close the ticket.

**Comment by TomasVotruba** [comment]
If you ever need to upgrade more  `create_function` cases, [Rector does it pretty well](https://github.com/rectorphp/rector/commit/3376254f7742abab3fde0a865ae4de8a420e964f).
