### ISSUE TITLE
Enhance project description

### ISSUE THREAD

**Issue by c33s** [phpseclib/mcrypt_compat#16]
as php 7.2 removed mcrypt support entirely it would be good to see if this lib is a drop-in replacement to get old code run again. i first only read the github project description and thought this lib is only for backporting mcrypt to php5.

github desc:

> PHP 5.x polyfill for mcrypt extension. 

readme:

> PHP 5.x/7.x polyfill for mcrypt extension.

packagist:

> PHP 7.1 polyfill for the mcrypt extension from PHP <= 7.0

**Comment by terrafrost** [comment]
I've made all the various descriptions more consistent (matches the readme).

Thanks!
