### ISSUE TITLE
stream_filter_append output is different than original mcrypt when writing

### ISSUE THREAD

**Issue by Algent** [phpseclib/mcrypt_compat#18]
Hi,

I ran into some trouble on both PHP 5.6 and PHP 7.2 while trying to use the mcrypt_compat filters for stream_filter_append.

When writing, the end of encrypted data is missing from the file and then of course from the decrypted data as well.
Meanwhile reading a file encrypted with original mcrypt work correctly.

Here is an example:
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';

$data = "Hello, this a sample file content to be encrypted and decrypted.... END of file.";
$key = "ae6fa3da6ae39b05ce17e69d5e18c236a7341c80592626d81d7c70013b7d436d";
$iv = "5dc7a17ebe32b6e62f0b5f9519d57afb";
$opts = array('iv' => $iv, 'key' => $key, 'mode' => 'cbc');

$tmpPath = __DIR__ . '/tmp/';
if(!is_dir($tmpPath)) mkdir($tmpPath);
$srcFile = $tmpPath . 'data.txt';
$encryptedFile = $tmpPath . 'encrypted';
$decryptedFile = $tmpPath . 'decrypted.txt';

// Store data file
file_put_contents($srcFile, $data);

// encrypt the file
$in_enc = fopen($srcFile, 'rb');
$out_enc = fopen($encryptedFile, 'wb');
stream_filter_append($out_enc, 'convert.base64-encode');
stream_filter_append($out_enc, 'phpseclib.mcrypt.rijndael-256', STREAM_FILTER_WRITE, $opts);
while (!feof($in_enc)) {
    fwrite($out_enc, fread($in_enc, 1024));
}
fclose($in_enc);
fclose($out_enc);

// decrypt the file
$in_dec = fopen($encryptedFile, 'rb');
stream_filter_append($in_dec, 'phpseclib.mdecrypt.rijndael-256', STREAM_FILTER_READ, $opts);
stream_filter_append($in_dec, 'convert.base64-decode');
$out_dec = fopen($decryptedFile, 'wb');
while (!feof($in_dec)) {
    fwrite($out_dec, fread($in_dec, 1024));
}
fclose($in_dec);
fclose($out_dec);

// retrieve the decrypted file content
$out = "";
$fp = fopen($decryptedFile, 'r');
while (!feof($fp)) {
    $out .= fread($fp, 1024);
}
fclose($fp);

echo "Expected: \"$data\"" . PHP_EOL;
echo "Output  : \"$out\"" . PHP_EOL;

unlink($srcFile);
unlink($encryptedFile);
unlink($decryptedFile);

```
Output with **rijndael-256** cipher:
> Expected: "Hello, this a sample file content to be encrypted and decrypted.... END of file."
> Output  : "Hello, this a sample file content to be encrypted and decrypted.... END "

Output with **tripledes** cipher:
>Expected: "Hello, this a sample file content to be encrypted and decrypted.... END of file."
>Output  : "Hello, this a sample file content to be encrypted and decrypted.... END of fil"

Output with **shorter data string**:
>Expected: "Hello, this a sample file content.... END of file."
>Output  : "Hello, this a sample file content.... END of fil"

Changing the length of the data string or using another cipher doesn't seem to make the issue go away except if you accidentally match the length of the output (I think that's why it doesn't show up in the project unit tests).

If you replace the filtername to use mcrypt the same example seem to work properly. And if you compare both file it's really like a chunk is missing.

**Edit**: Tried to improve the example
After doing some additional search on this last night it I tried to add the "mode" option, look like it only happen in cbc mode.
I don't have enough knowledge to figure out if it's a "padding" issue but this code certainly doesn't seem to work like the regular mcrypt.

**Comment by terrafrost** [comment]
The issue should be fixed in https://github.com/terrafrost/mcrypt_compat/tree/invalid-length-cbc-streams .

Once I have a unit test to reproduce the issue I'll merge that branch into this repo.

Thanks!

**Comment by terrafrost** [comment]
The latest release should fix this.

Thanks!

**Comment by Algent** [comment]
Thanks a lot for this.
