### ISSUE TITLE
phpseclib_mcrypt_module_open CFB mapping missing from 1.0 branch

### ISSUE THREAD

**Issue by omniError** [phpseclib/mcrypt_compat#19]
A mapping needed to support CFB mode in mcrypt_module_open is on master but not 1.0. Compare:

master: https://github.com/phpseclib/mcrypt_compat/blob/master/lib/mcrypt.php#L271
1.0 branch: https://github.com/phpseclib/mcrypt_compat/blob/1.0/lib/mcrypt.php#L271

**Comment by omniError** [comment]
Reading this more, it looks like master is wrong, it should be passing the ints from the Base class and not strings. So 1.0 needs a line added to include
```php
'cfb' => Base::MODE_CFB8,
```

**Comment by terrafrost** [comment]
Good catch! I've fixed it in 1.0 and made a new release.

The master branch doesn't use phpseclib-2.0 - it uses phpseclib-master. phpseclib-master uses strings - not ints. So there's nothing to fix in the master branch as the newly added unit test demonstrates.

Thanks!
