### ISSUE TITLE
Fatal Error in Version 1.07

### ISSUE THREAD

**Issue by DouglasGreen** [phpseclib/mcrypt_compat#22]
In version 1.07, there is a typo in the source code that produces a fatal error: Undefined class constant 'MODE_CFB8' in vendor/phpseclib/mcrypt_compat/lib/mcrypt.php on line 275.

**Comment by terrafrost** [comment]
It looks like CFB8 was [added in phpseclib 2.0.11](https://github.com/phpseclib/phpseclib/releases/tag/2.0.11) - not 2.0.10 - and yet [composer.json#L25](https://github.com/phpseclib/mcrypt_compat/blob/1.0.7/composer.json#L25) is says >=2.0.10.

I'll update the composer.json and do a new release.

Thanks!

**Comment by terrafrost** [comment]
Should be better now.

Thanks!
