### ISSUE TITLE
Uncaught Error: Class 'phpseclib3\Crypt\Blowfish' not found in lib/mcryptcompat/mcrypt.php:307

### ISSUE THREAD

**Issue by seansan** [phpseclib/mcrypt_compat#29]
I can see use `phpseclib3\Crypt\Blowfish;` in `lib/mcryptcompat/mcrypt.php`

and I can find the missing class in the file `lib/phpseclib/Crypt/Blowfish.php`

so my question is: what am I missing here to get this error?

Help appreciated ;)

PHP Fatal error: Uncaught Error: Class 'phpseclib3\Crypt\Blowfish' not found in lib/mcryptcompat/mcrypt.php:307
Stack trace:
#0 lib/mcryptcompat/mcrypt.php(1251): phpseclib_mcrypt_module_open('blowfish', '', 'ecb', '')
#1 lib/Varien/Crypt/Mcrypt.php(77): mcrypt_module_open('blowfish', '', 'ecb', '')
#2 app/code/core/Mage/Core/Model/Encryption.php(174): Varien_Crypt_Mcrypt->init('0d5a5169c64edaa...')
#3 app/code/core/Mage/Core/Model/Encryption.php(198): Mage_Core_Model_Encryption->_getCrypt()
#4 app/code/core/Mage/Core/Helper/Data.php(242): Mage_Core_Model_Encryption->decrypt('FltGPeVKbgKAPZo...')
#5 app/code/community/Ebizmarts/MailChimp/Helper/Data.php(378): Mage_Core_Helper_Data->decrypt('FltGPeVKbgKAPZo...')
#6 app/code/community/Ebizmarts/MailChimp/Helper/Data.ph in lib/mcryptcompat/mcrypt.php on line 307

![image](https://user-images.githubusercontent.com/652395/94734053-ee094880-0368-11eb-9930-acab51e4f50c.png)

![image](https://user-images.githubusercontent.com/652395/94734418-7d166080-0369-11eb-81ee-19eed69aa458.png)

**Comment by terrafrost** [comment]
I just tried it out and didn't have any issues. I did `composer require phpseclib/phpseclib:dev-master && composer require phpseclib/mcrypt_compat:dev-master`. I then ran this script:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

mcrypt_module_open('blowfish', '', 'ecb', '');
```
I didn't get any errors.

So I guess mcrypt_compat was installed though Composer - was phpseclib / dev-master?

**Comment by seansan** [comment]
OK ... I will close this. Must be something with versioning - master against master dev .. or dev. Sorry. And thanks for confirming!
