### ISSUE TITLE
THANKYOU!!!!!!

### ISSUE THREAD

**Issue by RickKukiela** [phpseclib/mcrypt_compat#30]
Not sure where else to put this. No issue. Just wanted to say THANK YOU SO MUCH for this... you literally saved my ass. Upgraded the server to php7.4 and found out weeks later that one part of one site that used mcrypt had been broken. This library saved me hours or pain porting the code my self. Is there a link where I can send yall a beer or something?

**Comment by terrafrost** [comment]
Thank you for the positive feedback - it's much appreciated 😊

For beer money lol (I'm more of a hard seltzer person myself haha) you can use http://paypal.me/phpseclib !

Thanks!!
