### ISSUE TITLE
php 8.1 compatibility issues

### ISSUE THREAD

**Issue by Flyingmana** [phpseclib/mcrypt_compat#32]
Hi, we noticed a compatibility issue with 8.1

> Return type of phpseclib_mcrypt_filter::filter($in, $out, &$consumed, $closing) should either be compatible with php_user_filter::filter($in, $out, &$consumed, bool $closing): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

>  Return type of phpseclib_mcrypt_filter::onCreate() should either be compatible with php_user_filter::onCreate(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

**Comment by terrafrost** [comment]
I used the new `#[\ReturnTypeWillChange]` attribute to fix the issue. Making it compatible with PHP 8.1's definition for `php_user_filter::onCreate()` will cause issues with older versions of PHP that this library is compatible with.

It'd be nice to add PHP 8.1 to the unit tests but alas TravisCI doesn't yet support PHP 8.1. There are also apparently not yet [official Docker containers](https://hub.docker.com/_/php) available for PHP 8.1!

I'll try to do a release this evening!

**Comment by terrafrost** [comment]
1.0.12 and 2.0.1 have been tagged and released!

**Comment by cfletcher** [comment]
Sorry to post on a closed issue, but is the lib compatible with PHP 8.0? The comments in https://github.com/phpseclib/mcrypt_compat/blob/master/lib/mcrypt.php say 5 and 7 but not 8.0!

**Comment by terrafrost** [comment]
It's compatible. In fact, it's passing the unit tests on 8.0 and 8.1:

https://app.travis-ci.com/github/phpseclib/mcrypt_compat

Really I'd just ignore that line. phpseclib/phpseclib has a ton of files with that line in it and I don't really feel like updating them en masse to add PHP 8. I guess a simple enough sed script could be employed but...  someone else can do it.

If you want to submit a PR to this project to remove that line feel free!

**Comment by terrafrost** [comment]
@cfletcher - It's compatible. In fact, it's passing the unit tests on 8.0 and 8.1:

https://app.travis-ci.com/github/phpseclib/mcrypt_compat

Really I'd just ignore that line. phpseclib/phpseclib has a ton of files with that line in it and I don't really feel like updating them en masse to add PHP 8. I guess a simple enough sed script could be employed but...  someone else can do it.

If you want to submit a PR to this project to remove that line feel free!
