### ISSUE TITLE
OFB mode - Uncaught TypeError: Argument 1 passed to mcrypt_enc_get_iv_size() must be an instance of phpseclib3\Crypt\Common\SymmetricKey, bool given

### ISSUE THREAD

**Issue by consolibyte** [phpseclib/mcrypt_compat#33]
This code produces an error with `mcrypt_compat`, but works with PHP `mcrypt`: 

```

$crypt = mcrypt_module_open('rijndael-256', '', 'ofb', '');
$iv_size = mcrypt_enc_get_iv_size($crypt);
$ks = mcrypt_enc_get_key_size($crypt);

mcrypt_generic_init($crypt, $key, $iv);
$decrypted = trim(mdecrypt_generic($crypt, $encrypted));

print('DECRYPT=' . $decrypted);
```

The error produced is: 

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to mcrypt_enc_get_iv_size() must be an instance of phpseclib3\Crypt\Common\SymmetricKey, bool given, called in /var/www/docker/sandbox/phpseclib2/test.php on line 48 and defined in /var/www/docker/sandbox/phpseclib2/vendor/phpseclib/mcrypt_compat/lib/mcrypt.php:1264
Stack trace:
#0 /var/www/docker/sandbox/phpseclib2/test.php(48): mcrypt_enc_get_iv_size(false)
#1 {main}
  thrown in /var/www/docker/sandbox/phpseclib2/vendor/phpseclib/mcrypt_compat/lib/mcrypt.php on line 1264

Fatal error: Uncaught TypeError: Argument 1 passed to mcrypt_enc_get_iv_size() must be an instance of phpseclib3\Crypt\Common\SymmetricKey, bool given, called in /var/www/docker/sandbox/phpseclib2/test.php on line 48 and defined in /var/www/docker/sandbox/phpseclib2/vendor/phpseclib/mcrypt_compat/lib/mcrypt.php on line 1264

TypeError: Argument 1 passed to mcrypt_enc_get_iv_size() must be an instance of phpseclib3\Crypt\Common\SymmetricKey, bool given, called in /var/www/docker/sandbox/phpseclib2/test.php on line 48 in /var/www/docker/sandbox/phpseclib2/vendor/phpseclib/mcrypt_compat/lib/mcrypt.php on line 1264

Call Stack:
    0.0005     390408   1. {main}() /var/www/docker/sandbox/phpseclib2/test.php:0
    0.0176     624728   2. mcrypt_enc_get_iv_size($td = FALSE) /var/www/docker/sandbox/phpseclib2/test.php:48
```

Is there a way to make this work?

**Comment by terrafrost** [comment]
So I wouldn't really call this a bug since https://github.com/phpseclib/mcrypt_compat doesn't mention support for ofb. phpseclib supports mcrypt's _nofb_ mode but not it's _ofb_ mode.

Now mcrypt_compat _does_ implement cfb and ncfb. That corresponds to phpseclib's CFB8 and CFB modes, respectively. I can look into adding support for OFB8 (what mcrypt's ofb8 more accurately corresponds to) and model it after https://github.com/phpseclib/phpseclib/pull/1257/commits/8e6948fdd218ad90360335a16599c79ed906e940 .

I do have some other higher priority phpseclib related stuff I'm working on, however, so, baring a [patreon donation](https://www.patreon.com/phpseclib) to motivate me lol I can't give you an ETA. Maybe a few weeks? idk

**Comment by consolibyte** [comment]
I sort of figured it was going to be a "not supported" thing vs. a bug - that's helpful to have confirmed, thanks! 

This is definitely important to our company - it would make some migration of some existing legacy code _much_ easier for us. 

It's a little hard for me to get _recurring_ donations approved, but do you know if Patreon will let us do a one-time donation? Or pay yearly instead of monthly? I would certainly get a one-time somewhere in the $500 or $750 range approved if that helps keep this on your radar? Thoughts?

**Comment by terrafrost** [comment]
For $750 I'll try to have it done by early next week! :D

For a one time payment you could PayPal me. But hold off until I've actually done the work! I'll get started when I get home from work today!

**Comment by consolibyte** [comment]
Awesome! I have it approved on my end - if we can get stuff we had previously encrypted with `rijndael-256` in `ofb` decrypted without depending on `mcrypt`, that would make it nice and quick for us to pull `mcrypt` out of our Docker images for sure!

**Comment by terrafrost** [comment]
The newest release of mcypt_compat should have full support for `ofb`!

**Comment by consolibyte** [comment]
WOOHOO! THANKS! Can you send me your PayPal address? (Or reach out to me at keithp@ChargeOver.com if you want to keep the email adddr off the issue?)

**Comment by terrafrost** [comment]
jjwiggie@gmail.com is my address! https://sourceforge.net/donate/index.php?group_id=198487 is a direct link you can use to do the donation.

Thanks!

**Comment by consolibyte** [comment]
THANK YOU! Donation made, happy to be able to support great projects like this! We will pull this down and test soon!

**Comment by terrafrost** [comment]
Got the money - thanks!

I also added y'all to the sponsor list!:

https://github.com/phpseclib/phpseclib/commit/bd8f02906e0a744838cdcf5cf10476638f3066e0
