### ISSUE TITLE
PHP 8.1 deprecation warnings

### ISSUE THREAD

**Issue by diggersworld** [phpseclib/mcrypt_compat#34]
Hello, when using this package I'm seeing the following deprecation warning:

`8192: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/phpseclib/mcrypt_compat/lib/mcrypt.php line 650`

I've seen that similar issues have been resolved on the underlying library ([referenced here](https://github.com/phpseclib/phpseclib/issues/1770)) and was just wondering if/when they would be resolved for this additional package.

Thanks.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/mcrypt_compat/commit/e38b76f02e6cf97aca05f5738eee1b917d922101 should fix this.

Thanks!

**Comment by diggersworld** [comment]
Awesome thanks, I can confirm that's working for me. I did however have to pull `2.0.x-dev`, do you need to make a release?

**Comment by terrafrost** [comment]
I'll try to do a release for this and phpseclib in the next few days. Kinda silly to do a release for mcrypt_compat but not do one for phpseclib for the exact same issue!

**Comment by terrafrost** [comment]
I released a new version.

Thanks!
