### ISSUE TITLE
Php 8.1 deprecation warning

### ISSUE THREAD

**Issue by aszenz** [phpseclib/mcrypt_compat#36]
1x: Method "php_user_filter::onClose()" might add "void" as a native return type declaration in the future. Do the same in child class "phpseclib_mcrypt_filter" now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by terrafrost** [comment]
What version of mcrypt_compat are you using? From the most recent commit from the 1.0.14 release:

https://github.com/phpseclib/mcrypt_compat/blob/e38b76f02e6cf97aca05f5738eee1b917d922101/lib/mcrypt.php#L1253-L1254

That should prevent the deprecation warning.

For good measure I just tested it out. _With_ `#[\ReturnTypeWillChange]` I did not get the warning, with_out_ it I did.

**Comment by aszenz** [comment]
The latest version i see is 2.0.3 on Github, installing 2.0.3 shows the same error. When i add `@return void` to the method, the error goes away, not sure what is the reason, i'm getting the deprecation message when running tests via phpunit

**Comment by terrafrost** [comment]
Can you share the output of your `php -i`?

What you're describing just doesn't jibe. So I created the following script:

```php
<?php

class DemoFilter extends php_user_filter
{
    #[\ReturnTypeWillChange]
    public function filter($in, $out, &$consumed, $closing)
    {
    }

    /**
     * @return void
     */
    public function onCreate()
    {
    }

    public function onClose()
    {
    }
}
```
Here it's being ran on PHP 8.1: https://3v4l.org/kaChc

The output is as follows:

```
Deprecated: Return type of DemoFilter::onCreate() should either be compatible with php_user_filter::onCreate(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /in/kaChc on line 13

Deprecated: Return type of DemoFilter::onClose() should either be compatible with php_user_filter::onClose(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /in/kaChc on line 17
```
ie. the only line that doesn't result in a Deprecated warning is the one that's doing `#[\ReturnTypeWillChange]`. I'm guessing on yours it'd be the one that's doing `@return void`?

I mean, I can do `@return void` but I want to better understand the problem, first. Like what if this is an Ubuntu modified PHP version? In that scenario a bug report against the Ubuntu package maintainer might be appropriate in addition to doing `@return void`.

**Comment by aszenz** [comment]
Thanks, I tried this in an isolated project and there is no deprecation for `#[ReturnTypeWillChange]` attribute while there is one for annotation.
