### ISSUE TITLE
I have legacy system that has data already encrypt, Wanted to decrypt all inside php8 

### ISSUE THREAD

**Issue by KhairulAzmi21** [phpseclib/mcrypt_compat#40]
I try the code below , but does not working to decypt data that has been encrpyted during legacy system .I believe legacy system using php7.1 

anyone could explain why ?

````
if (!function_exists('decrypt')) {
    function decrypt($data, $key = '@bMp74Gx7k3E#2f6')
    {
        
        $module = @mcrypt_module_open('rijndael-256', '', MCRYPT_MODE_CBC, '');
        $key = byteSubstr($key, 0, mcrypt_enc_get_key_size($module));
        $ivSize = mcrypt_enc_get_iv_size($module);
        $iv = byteSubstr($data, 0, $ivSize);
        mcrypt_generic_init($module, $key, $iv);
        $decrypted = mdecrypt_generic($module, byteSubstr($data, $ivSize, byteLength($data)));
        mcrypt_generic_deinit($module);
        mcrypt_module_close($module);
        return rtrim($decrypted, "\0");
    }
}
```
```

if (!function_exists('byteSubstr')) {
    /**
     * Extract substring based on byte length.
     *
     * @param string $string
     * @param int $start
     * @param int $length
     * @param string $encoding
     * @return string
     */
    function byteSubstr($string, $start, $length = null)
    {
        if ($length === null) {
            $length = byteLength($string);
        }

        return mb_substr((string)$string, $start, $length, '8bit');
    }
}

```
```
if (!function_exists('byteLength')) {
    /**

     * Get the byte length of a string.
     *
     * @param string $string
     * @return int
     */
    function byteLength($string)
    {
        return mb_strlen((string)$string, '8bit');
    }
}
```

**Comment by terrafrost** [comment]
Can you provide a base64 encoded ciphertext string that successfully decrypts with mcrypt but not with mcrypt_compat?

Thanks!

**Comment by KhairulAzmi21** [comment]
`$data = 'Wd³FDÂ*áh[Í°ãÏá¿#Ý/¿q¦±½í¼TLîÄ(ÙçUÓWÈ`V?ä×P´O[L§';
	error_reporting(E_ALL & ~E_DEPRECATED);
                     $amount = $this->decryptColumn($data);
                error_reporting(E_ALL);       
	var_dump($amount);`
	
`'Wd³FDÂ*áh[Í°ãÏá¿#Ý/¿q¦±½í¼TLîÄ(ÙçUÓWÈ`V?ä×P´O[L§'`

**Comment by KhairulAzmi21** [comment]
should return 1200

**Comment by KhairulAzmi21** [comment]
but return this instead 
`b"Ol
\x7F
Å
\x1D\x0F
;╠
\x07
+K╔ıÛ└:§öQ¨¤.■D
\e
Teãhk
\x0E
;¢ò┘éÀ
\x07
0øE┘!«Y▄éïI4ö5ëüÎ┤X
\x16
┤│
\x1E
dñ¨È¼i@┤e'mÆó╔þ‗█
\x0E
ãøà╦Ag╠%¹)xµ·pnrI"`

**Comment by terrafrost** [comment]
When I tried to run it with *actual* mcrypt (using [PHP 5.6](https://github.com/phpseclib/docker-php/tree/5.6)) I got gibberish. My code:

```php
<?php
$data = 'Wd³FDÂ*áh[Í°ãÏá¿#Ý/¿q¦±½í¼TLîÄ(ÙçUÓWÈ`V?ä×P´O[L§';

    function decrypt($data, $key = '@bMp74Gx7k3E#2f6')
    {

        $module = @mcrypt_module_open('rijndael-256', '', MCRYPT_MODE_CBC, '');
        $key = byteSubstr($key, 0, mcrypt_enc_get_key_size($module));
        $ivSize = mcrypt_enc_get_iv_size($module);
        $iv = byteSubstr($data, 0, $ivSize);
        mcrypt_generic_init($module, $key, $iv);
        $decrypted = mdecrypt_generic($module, byteSubstr($data, $ivSize, byteLength($data)));
        mcrypt_generic_deinit($module);
        mcrypt_module_close($module);
        return rtrim($decrypted, "\0");
    }

    function byteSubstr($string, $start, $length = null)
    {
        if ($length === null) {
            $length = byteLength($string);
        }

        return mb_substr((string)$string, $start, $length, '8bit');
    }

    function byteLength($string)
    {
        return mb_strlen((string)$string, '8bit');
    }

    echo decrypt($data);
```
That said, I can't be sure that non-printable characters are being mangled in the ciphertext that you posted. That's why I asked you to base64 encode the plaintext. ie. instead of doing this:

```
$data = 'Wd³FDÂ*áh[Í°ãÏá¿#Ý/¿q¦±½í¼TLîÄ(ÙçUÓWÈ`V?ä×P´O[L§';
```
Do this:

```
$data = base64_decode('...');
```

**Comment by KhairulAzmi21** [comment]
<img width="206" alt="Screenshot 2024-10-07 at 14 06 54" src="https://github.com/user-attachments/assets/f83c1676-3835-4af7-bfb3-c7d33f68c487">

this value comes from data in table mysql ..

**Comment by KhairulAzmi21** [comment]
this is the value 
`wodXZMKzRsKJRMOCKsOhaFvDjcKww6PDj8KLw6HCv8KLI8Odwo8vwr9xwqbCscK9w63CvFRMw64MGcOEKMKRf8KGw5nDp1UVw5NXw4hgAlYLP8Okw5fCn1DCtE9bwpNMwoDCpw==`

**Comment by KhairulAzmi21** [comment]
<img width="495" alt="Screenshot 2024-10-07 at 14 10 07" src="https://github.com/user-attachments/assets/14cac9ef-afd7-461b-ac8d-eecca510cc48">

this one using mcrypt in php7.2 . it works .

**Comment by terrafrost** [comment]
idk what `$this->decryptColumn()` does. The code you posted doesn't contain a class. If you could post _standalone_ code that successfully decrypts the ciphertext I can proceed from there but as is you haven't.

Even with base64_decode()'ing the base64_encode()'d string you posted I'm still not able to get the code that you've posted to decrypt anything with the _original_ mcrypt:

```php
<?php
$data = base64_decode('wodXZMKzRsKJRMOCKsOhaFvDjcKww6PDj8KLw6HCv8KLI8Odwo8vwr9xwqbCscK9w63CvFRMw64MGcOEKMKRf8KGw5nDp1UVw5NXw4hgAlYLP8Okw5fCn1DCtE9bwpNMwoDCpw==');

    function decrypt($data, $key = '@bMp74Gx7k3E#2f6')
    {

        $module = @mcrypt_module_open('rijndael-256', '', MCRYPT_MODE_CBC, '');
        $key = byteSubstr($key, 0, mcrypt_enc_get_key_size($module));
        $ivSize = mcrypt_enc_get_iv_size($module);
        $iv = byteSubstr($data, 0, $ivSize);
        mcrypt_generic_init($module, $key, $iv);
        $decrypted = mdecrypt_generic($module, byteSubstr($data, $ivSize, byteLength($data)));
        mcrypt_generic_deinit($module);
        mcrypt_module_close($module);
        return rtrim($decrypted, "\0");
    }

    function byteSubstr($string, $start, $length = null)
    {
        if ($length === null) {
            $length = byteLength($string);
        }

        return mb_substr((string)$string, $start, $length, '8bit');
    }

    function byteLength($string)
    {
        return mb_strlen((string)$string, '8bit');
    }

    echo decrypt($data);
```

Here's the version of PHP I'm now using:

```
PHP 7.2.34 (cli) (built: Dec 11 2020 10:44:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by terrafrost** [comment]
Like I'm assuming that the key is `@bMp74Gx7k3E#2f6`. Is it? Or when you're calling your `decrypt()` method are you passing that second parameter? If you are then I obviously would not be able to decrypt any ciphertext encrypted with that key that is unknown to me...

**Comment by KhairulAzmi21** [comment]
Actually it was working , 

legacy code does wrap the value inside `utf8_decode($data); `

when im doing this it working fine . 

Thanks for help ! .
