### ISSUE TITLE
Remove error-suppressor and use exceptions instead

### ISSUE THREAD

**Issue by tomsommer** [phpseclib/mcrypt_compat#5]
There is a massive use of the @-error-suppressor in this lib, these should be removed as they make performance suffer.

trigger_error() should also be replaced with Exceptions.

**Comment by terrafrost** [comment]
mcrypt, however, doesn't throw exceptions, so for this implementation to be as faithful as possible, it can't throw exceptions either.

You throw an exception and you have to catch it. But if an error message is simply shown then no catching is necessary. The error message is displayed (assuming it isn't suppressed) and the program continues running as normal.

If the goal was to write a whole new crypto API from scratch, I'd agree with you. But that's not the goal of this project. The goal of this project is to provide a drop in library that can be used in mcrypt's stead.

**Comment by tomsommer** [comment]
Makes sense

**Comment by terrafrost** [comment]
Yah...  I think it's an artifact of PHP4 days but mcrypt dates back to PHP4 days so
