### ISSUE TITLE
The package is not full

### ISSUE THREAD

**Issue by AliceMakk** [phpseclib/mcrypt_compat#7]
Hello there,

When I install it through composer I don't get the full **mcrypt.php** as it is in your published folder. For example, I don't see:
`function mcrypt_get_iv_size($cipher, $mode)
    {
        return phpseclib_mcrypt_get_iv_size($cipher, $mode);
    }`
in the **mcrypt.php** when I installed through composer however see it in the zip archive.
So I had to manually upload the zip package and replace **mcrypt.php** with that which in the zip package.

Would it be possible to fix that please?

Thank you

**Comment by terrafrost** [comment]
Good observation - I've made a new release on packagist - thanks!
